
SELECT YEAR, monthly_sum, avg(monthly_sum)
	over( ORDER BY YEAR ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) as monthly_smooth_sum
FROM(
	SELECT SUM(DOSAGE_UNIT) as monthly_sum, YEAR
	FROM(
		SELECT DOSAGE_UNIT, YEAR(TRANSACTION_DATE) ||
		CASE 
		    WHEN (  CAST( MONTH(TRANSACTION_DATE) AS INT)  < 10 ) 
		         THEN '0'  || CAST( MONTH(TRANSACTION_DATE) AS INT)
		    ELSE CAST ( MONTH(TRANSACTION_DATE) AS CHAR(2) )
		END AS YEAR
		FROM cse532.dea_ny
	)
	GROUP BY YEAR
)